Ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
    # url(r'^static/(?P<path>.*)$', serve, {
    #     'document_root': settings.STATIC_ROOT,
    # }),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('test-page', views.test_page, name='test'),
    path('blog', views.blog, name='blog'),
    path('about-us', views.about_us, name='about-us'),

]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('add-to-wish-list', views.add_to_wishlist, name='add_to_wish_list'),
    path('cart', views.cart_view, name='cart'),
    path('cart-delete/<int:id>', views.cart_delete, name='cart-delete'),
    path('checkout', views.checkout, name='checkout'),
    path('cache_payment', views.cache_payment, name='cache_payment'),
    path('orders', views.orders_view, name='orders_view'),
    path('orders/<int:order_id>', views.orders_view, name='orders_view'),
    path('wishlist', views.wishlist_view, name='wishlist_view'),
    path('wishlist-delete/<int:id>', views.wishlist_delete, name='wishlist-delete'),
    path('category/<str:category_slug>', views.list_category, name='list_category'),
    path('<str:slug>', views.product_view, name='view_product'),
    path('new_arrival/', views.new_arrival, name='new_arrival'),
    path('page404/', views.Page404, name='page404'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('my-account', views.my_account, name='my_account'),
    path('register', views.register_view, name='register'),
    path('address', views.address_view, name='address'),
    path('address/<int:pk>', views.address_view, name='address'),
    path('add-address', views.add_address, name='add_address'),
    path('delete-address/<int:pk>', views.delete_address, name='delete-address'),
]

templates/accounts/account.html
{% extends 'common/base.html' %}
{% load static %}
{% block body %}
    {#<body>#}
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Float four columns side by side */
        .column {
            float: left;
            width: 33%;
            padding: 0 10px;
            margin-bottom: 20px;
        }

        /* Remove extra left and right margins, due to padding */
        .row {
            margin: 0 -5px;
        }


        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive columns */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
                display: block;
                margin-bottom: 20px;
            }
        }

        /* Style the counter cards */
        .card {
            padding: 15px;
            border-radius: 5px;
            text-align: left;
            background-color: #fff;
            border: 2px solid #CF9163;
        }

        .card:hover {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 15px;
            text-align: left;
            background-color: #fff;
            border: 2px solid #CF9163;
        }

        .heading {
            border-bottom: 2px solid #CF9163;
        }

        .heading h3 {
            color: #0b0b0b;
            font-weight: 700;
            font-size: 16px;
        }

        .card p {
            color: #898989;
            font-size: 14px;
        }

        .card a {
            color: #106399;
        }

        .editLink {

        }

    </style>
    <body>
    {% include 'common/header.html' %}

    <div class="banner-wrapper has_background">
        <img src="{% static 'images/banner-for-all2.jpg' %}"
             class="img-responsive attachment-1920x447 size-1920x447" alt="">
        <div class="banner-wrapper-inner">
            <h1 class="page-title">My Account</h1>
            <div role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
            </div>
        </div>
    </div>
    <main class="site-main  main-container no-sidebar">
        <div class="container">
            <div class="row">
                <div class="main-content col-md-12">
                    <div class="page-main-content">
                        <div class="lynessa">
                            <nav class="lynessa-MyAccount-navigation">
                                <ul>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--orders">
                                        <a href="{% url 'shop:orders_view' %}">Orders</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--edit-address">
                                        <a href="{% url 'users:address' %}">Shipping Address</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--edit-account is-active">
                                        <a href="{% url 'users:my_account' %}">Account details</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--customer-logout">
                                        <a href="{% url 'users:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </nav>
                            {% if errors %}
                                {% for error in errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                            <div class="lynessa-MyAccount-content">
                                <div class="lynessa-notices-wrapper"></div>
                                <form class="lynessa-EditAccountForm edit-account" action="{% url 'users:my_account' %}" method="post">
                                    <div class="clear"></div>
                                    {% csrf_token %}
                                    <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                        <label for="account_display_name">Full name&nbsp;<span
                                                class="required">*</span></label>
                                        <input type="text" class="lynessa-Input lynessa-Input--text input-text"
                                               name="account_display_name" id="account_display_name" value="{{ request.user.full_name }}">
                                        <span><em>This will be how your name will be displayed in the account section and in reviews</em></span>
                                    </p>
                                    <div class="clear"></div>
                                    <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                        <label for="account_email">Email address&nbsp;<span
                                                class="required">*</span></label>
                                        <input type="email" class="lynessa-Input lynessa-Input--email input-text"
                                               name="account_email" id="account_email" autocomplete="email"
                                               value="{{ request.user.email }}">
                                    </p>
                                    <fieldset>
                                        <legend>Password change</legend>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="password_current">Current password (leave blank to leave
                                                unchanged)</label>
                                            <input type="password"
                                                   class="lynessa-Input lynessa-Input--password input-text"
                                                   name="password_current" id="password_current" autocomplete="off">
                                        </p>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="password_1">New password (leave blank to leave
                                                unchanged)</label>
                                            <input type="password"
                                                   class="lynessa-Input lynessa-Input--password input-text"
                                                   name="password_1" id="password_1" autocomplete="off">
                                        </p>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="password_2">Confirm new password</label>
                                            <input type="password"
                                                   class="lynessa-Input lynessa-Input--password input-text"
                                                   name="password_2" id="password_2" autocomplete="off">
                                        </p>
                                    </fieldset>
                                    <div class="clear"></div>
                                    <p>
                                        <input type="hidden" id="save-account-details-nonce"
                                               name="save-account-details-nonce" value="">
                                        <input type="hidden" name="_wp_http_referer" value="">
                                        <button type="submit" class="lynessa-Button button" name="save_account_details"
                                                value="Save changes">Save changes
                                        </button>
                                        <input type="hidden" name="action" value="save_account_details">
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
    </body>

    {#<a class="backtotop active" href="#">#}
    {#    <i class="fa fa-angle-up"></i>#}
    {#</a>#}
    {#<script src="assets/js/jquery-1.12.4.min.js"></script>#}
    {#<script src="assets/js/bootstrap.min.js"></script>#}
    {#<script src="assets/js/chosen.min.js"></script>#}
    {#<script src="assets/js/countdown.min.js"></script>#}
    {#<script src="assets/js/jquery.scrollbar.min.js"></script>#}
    {#<script src="assets/js/lightbox.min.js"></script>#}
    {#<script src="assets/js/magnific-popup.min.js"></script>#}
    {#<script src="assets/js/slick.js"></script>#}
    {#<script src="assets/js/jquery.zoom.min.js"></script>#}
    {#<script src="assets/js/threesixty.min.js"></script>#}
    {#<script src="assets/js/jquery-ui.min.js"></script>#}
    {#<script src="assets/js/mobilemenu.js"></script>#}
    {#<script src="assets/js/functions.js"></script>#}
    {#</body>#}
{% endblock %}
</html>

templates/accounts/add-address.html
{% extends 'common/base.html' %}
{% load static %}
{% block body %}
    {#<body>#}
    <body>
    {% include 'common/header.html' %}

    <div class="banner-wrapper has_background">
        <img src="{% static 'images/banner-for-all2.jpg' %}"
             class="img-responsive attachment-1920x447 size-1920x447" alt="img">
        <div class="banner-wrapper-inner">
            <h1 class="page-title">My Account</h1>
            <div role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
            </div>
        </div>
    </div>
    <main class="site-main  main-container no-sidebar">
        <div class="container">
            <div class="row">
                <div class="main-content col-md-12">
                    <div class="page-main-content">
                        <div class="lynessa">
                            <nav class="lynessa-MyAccount-navigation">
                                <ul>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--orders">
{#                                        <a href="{% url 'ecommerce:view_orders' %}">Orders</a>#}
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--edit-address">
                                        <a href="{% url 'users:address' %}">Addresses</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--edit-account is-active">
                                        <a href="{% url 'users:my_account' %}">Account details</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--customer-logout">
                                        <a href="{% url 'users:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </nav>
                            {% if errors %}
                                {% for error in errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                            {% if address %}
                                <div class="lynessa-MyAccount-content">
                                    <div class="lynessa-notices-wrapper"></div>
                                    <form class="lynessa-EditAccountForm edit-account"
                                          action="{% url 'users:add_address' %}" method="post">
                                        <div class="clear"></div>
                                        {% csrf_token %}
                                        <input type="hidden" name="_method" value="put"/>
                                        <input type="hidden"
                                               name="address_id" id="full_name" value="{{ address.id }}">
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_display_name">Full name&nbsp;<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--text input-text"
                                                   name="full_name" id="full_name" value="{{ address.full_name }}">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">House Number&nbsp;<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="house_number" id="house_number"
                                                   value="{{ address.house_number }}">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">Street&nbsp;<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="street" id="street"
                                                   value="{{ address.street }}">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">City<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="city" id="city"
                                                   value="{{ address.city }}">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">PIN<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="pin_code" id="pin_code"
                                                   value="{{ address.pin_code }}">
                                        </p>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">State<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="state" id="state"
                                                   value="{{ address.city }}">
                                        </p>

                                        <div class="clear"></div>
                                        <p>
                                            <button type="submit" class="lynessa-Button button"
                                                    name="save_account_details"
                                                    value="Save changes">Save changes
                                            </button>
                                            <input type="hidden" name="action" value="save_account_details">
                                        </p>
                                    </form>
                                </div>
                            {% else %}
                                <div class="lynessa-MyAccount-content">
                                    <div class="lynessa-notices-wrapper"></div>
                                    <form class="lynessa-EditAccountForm edit-account"
                                          action="{% url 'users:address' %}" method="post">
                                        <div class="clear"></div>
                                        {% csrf_token %}
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_display_name">Full name&nbsp;<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--text input-text"
                                                   name="full_name" id="full_name" value="">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">House Number&nbsp;<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="house_number" id="house_number"
                                                   value="">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">Street&nbsp;<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="street" id="street"
                                                   value="">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">City<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="city" id="city"
                                                   value="">
                                        </p>
                                        <div class="clear"></div>
                                        <p class="lynessa-form-row lynessa-form-row--wide form-row form-row-wide">
                                            <label for="account_email">State<span
                                                    class="required">*</span></label>
                                            <input type="text" class="lynessa-Input lynessa-Input--email input-text"
                                                   name="state" id="state"
                                                   value="">
                                        </p>

                                        <div class="clear"></div>
                                        <p>
                                            <input type="hidden" id="save-account-details-nonce"
                                                   name="save-account-details-nonce" value="">
                                            <input type="hidden" name="_wp_http_referer" value="">
                                            <button type="submit" class="lynessa-Button button"
                                                    name="save_account_details"
                                                    value="Save changes">Save changes
                                            </button>
                                            <input type="hidden" name="action" value="save_account_details">
                                        </p>
                                    </form>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
    </body>

    {#<a class="backtotop active" href="#">#}
    {#    <i class="fa fa-angle-up"></i>#}
    {#</a>#}
    {#<script src="assets/js/jquery-1.12.4.min.js"></script>#}
    {#<script src="assets/js/bootstrap.min.js"></script>#}
    {#<script src="assets/js/chosen.min.js"></script>#}
    {#<script src="assets/js/countdown.min.js"></script>#}
    {#<script src="assets/js/jquery.scrollbar.min.js"></script>#}
    {#<script src="assets/js/lightbox.min.js"></script>#}
    {#<script src="assets/js/magnific-popup.min.js"></script>#}
    {#<script src="assets/js/slick.js"></script>#}
    {#<script src="assets/js/jquery.zoom.min.js"></script>#}
    {#<script src="assets/js/threesixty.min.js"></script>#}
    {#<script src="assets/js/jquery-ui.min.js"></script>#}
    {#<script src="assets/js/mobilemenu.js"></script>#}
    {#<script src="assets/js/functions.js"></script>#}
    {#</body>#}
{% endblock %}
</html>

templates/accounts/address.html
{% extends 'common/base.html' %}
{% load static %}
{% block body %}
    {#<body>#}
<style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Float four columns side by side */
        .column {
            float: left;
            width: 33%;
            padding: 0 10px;
            margin-bottom: 20px;
        }

        /* Remove extra left and right margins, due to padding */
        .row {
            margin: 0 -5px;
        }


        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Responsive columns */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
                display: block;
                margin-bottom: 20px;
            }
        }

        /* Style the counter cards */
        .card {
            padding: 15px;
            border-radius: 5px;
            text-align: left;
            background-color: #fff;
            border: 2px solid #CF9163;
        }

        .card:hover {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 15px;
            text-align: left;
            background-color: #fff;
            border: 2px solid #CF9163;
        }

        .heading {
            border-bottom: 2px solid #CF9163;
        }

        .heading h3 {
            color: #0b0b0b;
            font-weight: 700;
            font-size: 16px;
        }

        .card p {
            color: #898989;
            font-size: 14px;
        }

        .card a {
            color: #106399;
        }

        .editLink {

        }

    </style>
    <body>
    {% include 'common/header.html' %}

    <div class="banner-wrapper has_background">
        <img src="{% static 'images/banner-for-all2.jpg' %}"
             class="img-responsive attachment-1920x447 size-1920x447" alt="">
        <div class="banner-wrapper-inner">
            <h1 class="page-title">My Account</h1>
            <div role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
            </div>
        </div>
    </div>
    <main class="site-main  main-container no-sidebar">
        <div class="container">
            <div class="row">
                <div class="main-content col-md-12">
                    <div class="page-main-content">
                        <div class="lynessa">
                            <nav class="lynessa-MyAccount-navigation">
                                <ul>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--orders ">
                                        <a href="{% url 'shop:orders_view' %}">Orders</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--edit-address is-active">
                                        <a href="{% url 'users:address' %}">Shipping Address</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--edit-account ">
                                        <a href="{% url 'users:my_account' %}">Account details</a>
                                    </li>
                                    <li class="lynessa-MyAccount-navigation-link lynessa-MyAccount-navigation-link--customer-logout">
                                        <a href="{% url 'users:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </nav>
                            <a href="{% url 'users:add_address' %}" class="btn btn-dark">Add Address</a><br><br>
                            <div class="lynessa-MyAccount-content">
                                <div class="lynessa-notices-wrapper"></div>
                                <div>
                                    <div class="row">
                                        {% for address in addresses %}
                                            <div class="column">
                                                <div class="card">
                                                    <div class="heading"><h3>{{ address.full_name }}</h3></div>
                                                    <p>{{ address.house_number }}, {{ address.street }}, {{ address.city }}, {{ address.state }}, {{ address.pin_code }}</p>
                                                    <p class="editLink"><a href="{% url 'users:address' address.id %}"> Edit </a> | <a href="{% url 'users:delete-address' address.id %}"> Remove </a></p>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    {% include 'common/footer.html' %}
    </body>
{% endblock %}
</html>