Ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
    # url(r'^static/(?P<path>.*)$', serve, {
    #     'document_root': settings.STATIC_ROOT,
    # }),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('test-page', views.test_page, name='test'),
    path('blog', views.blog, name='blog'),
    path('about-us', views.about_us, name='about-us'),

]

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.png"/>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/chosen.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/pe-icon-7-stroke.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.scrollbar.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/lightbox.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/magnific-popup.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/slick.min.css"/>
    <link rel="stylesheet" type="text/css" href="/static/fonts/flaticon.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/megamenu.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/dreaming-attribute.css"/>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css"/>
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* Float four columns side by side */
        .column {
            float: left;
            width: 50%;
            padding: 0 10px;
            margin-bottom: 20px;
        }

        /* Remove extra left and right margins, due to padding */
        .row {
            margin: 0 -5px;
        }


        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }


        /* Responsive columns */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
                display: block;
                margin-bottom: 20px;
            }
        }

        /* Style the counter cards */
        .card {
            padding: 15px;
            border-radius: 5px;
            text-align: left;
            background-color: #fff;
            border: 2px solid #CF9163;
        }


        .card:hover {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 15px;
            text-align: left;
            background-color: #fff;
            border: 2px solid #CF9163;
        }

        .heading {
            border-bottom: 2px solid #CF9163;
        }

        .heading h3 {
            color: #0b0b0b;
            font-weight: 700;
            font-size: 16px;
        }

        .card p {
            padding: 10px;
            color: #4c4c4c;
            font-size: 20px;
            font-family: 'Hind', sans-serif;;
        }

        .card li {
            margin-top: 8px;
            margin-left: 12px;
            color: #4c4c4c;
            font-size: 20px;
            font-family: 'Hind', sans-serif;;
        }

        .card a {
            color: #106399;
        }

        .editLink {

        }

@media (max-width: 1499px) {
	.box-header-nav .main-menu > .menu-item {
		padding: 0 5px !important;
	}
}
    </style>
    <title>Miski E-Comm</title>
</head>
{% block body %}
{% endblock %}

<script src="/static/js/jquery-1.12.4.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/chosen.min.js"></script>
<script src="/static/js/countdown.min.js"></script>
<script src="/static/js/jquery.scrollbar.min.js"></script>
<script src="/static/js/lightbox.min.js"></script>
<script src="/static/js/magnific-popup.min.js"></script>
<script src="/static/js/slick.js"></script>
<script src="/static/js/jquery.zoom.min.js"></script>
<script src="/static/js/threesixty.min.js"></script>
<script src="/static/js/jquery-ui.min.js"></script>
<script src="/static/js/mobilemenu.js"></script>
<script src="/static/js/functions.js"></script>

templates/common/footer.html
{% load static %}
<footer id="footer" class="footer style-04">
    <div class="section-025">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-12 d-lg-none">
                    <div class="logo-footer">
                        <img src="{% static 'images/logo.png' %}"
                             class="az_single_image-img attachment-full" alt="img">
                    </div>
                    <div class="lynessa-socials style-01">
                        <div class="content-socials">
                            <ul class="socials-list">
                                <li>
                                    <a href="https://facebook.com/" target="_blank">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/" target="_blank">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/" target="_blank">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.pinterest.com/" target="_blank">
                                        <i class="fa fa-pinterest-p"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 d-none d-lg-block">
                    <div class="logo-footer">
                        <img style="margin: auto; width: 100px" src="{% static 'images/logo.png' %}"
                             class="az_single_image-img attachment-full" alt="img">
                    </div>
                    <div class="footer-desc">Ayush Ecomm Helps you to live a better life.<br/>
                    </div>
                    <div class="lynessa-socials style-01">
                        <div class="content-socials">
                            <ul class="socials-list">
                                <li>
                                    <a href="https://facebook.com/" target="_blank">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/" target="_blank">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/" target="_blank">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.pinterest.com/" target="_blank">
                                        <i class="fa fa-pinterest-p"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section-016">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
{#                    <p>© Copyright 2020 <a href="#">Ayush Ecomm Pvt. Ltd.</a>. All Rights Reserved.</p>#}
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="footer-device-mobile">
    <div class="wapper">
        <div class="footer-device-mobile-item device-home">
            <a href="{% url 'home:home' %}">
					<span class="icon">
						<span class="pe-7s-home"></span>
					</span>
                Home
            </a>
        </div>
{#        <div class="footer-device-mobile-item device-home device-wishlist">#}
{#            <a href="wishlist.html">#}
{#					<span class="icon">#}
{#						<span class="pe-7s-like"></span>#}
{#					</span>#}
{#                Wishlist#}
{#            </a>#}
{#        </div>#}
        <div class="footer-device-mobile-item device-home device-cart">
{#            <a href="{% url 'ecommerce:cart' %}">#}
					<span class="icon">
						<span class="pe-7s-shopbag"></span>
						<span class="count-icon">
							0
						</span>
					</span>
                <span class="text">Cart</span>
{#            </a>#}
        </div>
        <div class="footer-device-mobile-item device-home device-user">
{#            <a href="{% url 'my_account' %}">#}
					<span class="icon">
						<span class="pe-7s-user"></span>
					</span>
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.full_name }}
                    {% else %}
                    Login/Register
                {% endif %}
{#            </a>#}
        </div>
    </div>
</div>
<a href="#" class="backtotop active">
    <i class="fa fa-angle-up"></i>
</a>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>