Ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.static import serve


urlpatterns = [
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('account/', include('users.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
    # url(r'^static/(?P<path>.*)$', serve, {
    #     'document_root': settings.STATIC_ROOT,
    # }),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# else:
#     urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('test-page', views.test_page, name='test'),
    path('blog', views.blog, name='blog'),
    path('about-us', views.about_us, name='about-us'),

]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('add-to-wish-list', views.add_to_wishlist, name='add_to_wish_list'),
    path('cart', views.cart_view, name='cart'),
    path('cart-delete/<int:id>', views.cart_delete, name='cart-delete'),
    path('checkout', views.checkout, name='checkout'),
    path('cache_payment', views.cache_payment, name='cache_payment'),
    path('orders', views.orders_view, name='orders_view'),
    path('orders/<int:order_id>', views.orders_view, name='orders_view'),
    path('wishlist', views.wishlist_view, name='wishlist_view'),
    path('wishlist-delete/<int:id>', views.wishlist_delete, name='wishlist-delete'),
    path('category/<str:category_slug>', views.list_category, name='list_category'),
    path('<str:slug>', views.product_view, name='view_product'),
    path('new_arrival/', views.new_arrival, name='new_arrival'),
    path('page404/', views.Page404, name='page404'),
]

templates/ecommerce/checkout.html
{% extends 'common/base.html' %}
{% load static %}
{% block body %}
    <body>
    {% include 'common/header.html' %}
    <div class="banner-wrapper has_background">
        <img src="{% static 'images/banner-for-all2.jpg' %}"
             class="img-responsive attachment-1920x447 size-1920x447" alt="">
        <div class="banner-wrapper-inner">
            <h1 class="page-title">Checkout</h1>
            <div role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
                <ul class="trail-items breadcrumb">
                    <li class="trail-item trail-begin"><a href="indexs.html"><span>Home</span></a></li>
                    <li class="trail-item trail-end active"><span>Cart</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <main class="site-main  main-container no-sidebar">
        <div class="container">
            <div class="row">
                <div class="main-content col-md-12">
                    <div class="page-main-content">
                        <div class="lynessa">
                            <div class="lynessa-notices-wrapper"></div>
                            <div name="checkout" method="post" class="checkout lynessa-checkout"
                                 action="#" enctype="multipart/form-data"
                                 novalidate="novalidate">
                                <h3 id="order_review_heading">Your order</h3>
                                <div id="order_review" class="lynessa-checkout-review-order">
                                    <table class="shop_table lynessa-checkout-review-order-table">
                                        <thead>
                                        <tr>
                                            <th class="product-name">Product</th>
                                            <th class="product-total">Total</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for product in cart_products %}
                                        <tr class="cart_item">
                                            <td class="product-name">
                                                {{ product.product.name }}&nbsp;&nbsp; <strong class="product-quantity">×
                                                {{ product.quantity }}</strong></td>
                                            <td class="product-total">
                                            <span class="lynessa-Price-amount amount"><span
                                                    class="lynessa-Price-currencySymbol">₹</span>{{ product.price }}</span>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                        <tr class="cart-subtotal">
                                            <th>Subtotal</th>
                                            <td><span class="lynessa-Price-amount amount"><span
                                                    class="lynessa-Price-currencySymbol">₹</span>{{ cart.total_price }}</span>
                                            </td>
                                        </tr>
                                        <tr class="order-total">
                                            <th>Total</th>
                                            <td><strong><span class="lynessa-Price-amount amount"><span
                                                    class="lynessa-Price-currencySymbol">₹</span>{{ cart.total_price }}</span></strong>
                                            </td>
                                        </tr>
{#                                        <tr class="order-total">#}
{#                                            <th>Choose Address</th>#}
{#                                            <td>#}
{#                                                <select class="order-total" name="cars" id="cars">#}
{#                                                    <option value="volvo">Volvo</option>#}
{#                                                    <option value="saab">Saab</option>#}
{#                                                    <option value="opel">Opel</option>#}
{#                                                    <option value="audi">Audi</option>#}
{#                                                </select>#}
{#                                            </td>#}
{#                                        </tr>#}
                                        </tfoot>
                                    </table>
                                    <input type="hidden" name="lang" value="en">
                                    <form class="order-total"
                                          action="{% url 'shop:cache_payment' %}"
                                          method="POST">

                                        <script
                                                src="https://checkout.razorpay.com/v1/checkout.js"
                                                data-key="rzp_test_TF1tA8adBOjAEx"
                                                data-amount="{{ cart.total_price_in_paise }}"
                                                data-buttontext="Buy Now"
                                                data-name="Ayush Ecomm"
                                                data-description=""
                                                data-image="http://206.189.141.238/static/AdminPanel/icon.png"
                                                data-prefill.name="{{ request.user.name }}"
                                                data-prefill.email="{{ request.user.email }}"
                                                data-prefill.contact="8461034077"
                                                data-theme.color="#256d7b"
                                        ></script>
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ cart.price_in_paise }}" name="amount">
                                        <input type="hidden" value="{{ cart.id }}" name="cart">

                                        <input type="hidden" value="Hidden Element" name="hidden">

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer id="footer" class="footer style-01">

        <div class="section-010">

        </div>
    </footer>
    <div class="footer-device-mobile">
        <div class="wapper">
            <div class="footer-device-mobile-item device-home">
                <a href="index.html">
					<span class="icon">
						<span class="pe-7s-home"></span>
					</span>
                    Home
                </a>
            </div>
            <div class="footer-device-mobile-item device-home device-wishlist">
                <a href="wishlist.html">
					<span class="icon">
						<span class="pe-7s-like"></span>
					</span>
                    Wishlist
                </a>
            </div>
            <div class="footer-device-mobile-item device-home device-cart">
                <a href="cart.html">
					<span class="icon">
						<span class="pe-7s-shopbag"></span>
						<span class="count-icon">
							0
						</span>
					</span>
                    <span class="text">Cart</span>
                </a>
            </div>
            <div class="footer-device-mobile-item device-home device-user">
                <a href="my-account.html">
					<span class="icon">
						<span class="pe-7s-user"></span>
					</span>
                    Account
                </a>
            </div>
        </div>
    </div>
    {% include 'common/footer.html' %}
    </body>
{% endblock %}
<!-- Mirrored from ledthanhdat.vn/html/lynessa/checkout.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 08 Oct 2020 17:06:03 GMT -->
</html>

templates/ecommerce/order.html
{% extends 'common/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block body %}
    <body>
    {% include 'common/header.html' %}
    <div class="banner-wrapper has_background">
        <img src="{% static 'images/banner-for-all2.jpg' %}"
             class="img-responsive attachment-1920x447 size-1920x447" alt="">
        <div class="banner-wrapper-inner">
            <h1 class="page-title">Order #{{ order.id }}</h1>
            <div role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
            </div>
        </div>
    </div>
    <main class="site-main main-container no-sidebar">
        <div class="container">
            <div class="row">
                <div class="main-content col-md-12">
                    <div class="page-main-content">
                        <div class="lynessa">
                            <div class="lynessa-notices-wrapper"></div>
                            <form class="lynessa-cart-form">
                                <table class="shop_table shop_table_responsive cart lynessa-cart-form__contents"
                                       cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th class="product-name">Your Magic Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product-quantity">Quantity</th>
                                        <th class="product-subtotal">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for product in cart_products %}
                                        <tr class="lynessa-cart-form__cart-item cart_item">
                                            <td class="product-name" data-title="Product">
                                                <a href="#">{{ product.product.name }} * {{ product.quantity }}</a></td>
                                            <td class="product-price" data-title="Price">
                                        <span class="lynessa-Price-amount amount"><span
                                                class="lynessa-Price-currencySymbol">₹</span>{{ product.price }}</span></td>
                                            <td class="product-price" data-title="Quantity">
                                                <div class="control">
                                                    <span
                                                            class="lynessa-Price-currencySymbol">{{ order.cart.quantity }}</span>
                                                </div>
                                            </td>
                                            <td class="product-subtotal" data-title="Total">
                                        <span class="lynessa-Price-amount amount"><span
                                                class="lynessa-Price-currencySymbol">₹</span>{{ product.price }}</span>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="6" class="actions">
                                            </h4>
                                            <button type="submit" class="button" name="update_cart" value="Update cart"
                                                    disabled="">Total : {{ order.cart.total_price }}
                                            </button>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </form>
                            <div class="cart-collaterals">
                                <div class="cart_totals ">
                                    <h2>Order Status</h2>
                                    <table class="shop_table shop_table_responsive" cellspacing="0">
                                        <tbody>

                                        {% for status_update in order.order_histories %}
                                            <tr class="order-total">
                                                <th>{{ status_update.status_text }}</th>
                                                <td data-title="Total Investment"><strong><span
                                                        class="lynessa-Price-amount amount"><span
                                                        class="lynessa-Price-currencySymbol"></span>{{ status_update.updated_at }}</span></strong>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'common/footer.html' %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/chosen.min.js' %}"></script>
    <script src="{% static 'js/countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'js/lightbox.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/jquery.zoom.min.js' %}"></script>
    <script src="{% static 'js/threesixty.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/mobilemenu.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>
    </body>
{% endblock %}
</html>

templates/ecommerce/wishlist.html
{% extends 'common/base.html' %}
{% load static %}
{% block body %}
    <body>
    {% include 'common/header.html' %}
    <div class="banner-wrapper has_background">
        <img src="{% static 'images/banner-for-all2.jpg' %}"
             class="img-responsive attachment-1920x447 size-1920x447" alt="">
        <div class="banner-wrapper-inner">
            <h1 class="page-title">Wishlist</h1>
            <div role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs">
            </div>
        </div>
    </div>
    <main class="site-main  main-container no-sidebar">
    <div class="container">
        <div class="row">
            <div class="main-content col-md-12">
                <div class="page-main-content">
                    <form id="yith-wcwl-form" class="lynessa">
                        <!-- TITLE -->
                        <!-- WISHLIST TABLE -->
                        <table class="shop_table cart wishlist_table" data-pagination="no" data-per-page="5" data-page="1" data-id="" data-token="">
                            <thead>
                            <tr>
                                <th class="product-remove"></th>
                                <th class="product-thumbnail"></th>
                                <th class="product-name">
                                    <span class="nobr">Product Name</span>
                                </th>
                                <th class="product-price">
                    <span class="nobr">
                        Unit Price                    </span>
                                </th>
                                <th class="product-stock-status">
                    <span class="nobr">
                        Stock Status                    </span>
                                </th>
                                <th class="product-add-to-cart"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for product in request.user.wish_list.productss %}
                            <tr id="yith-wcwl-row-29" data-row-id="29">
                                <td class="product-remove">
                                    <div>
                                        <a href="#" class="remove remove_from_wishlist" title="Remove this product">×</a>
                                    </div>
                                </td>
                                <td class="product-thumbnail">
                                    <a href="{% url 'shop:view_product' product.product.slug %}">
                                        <img src="{{ product.product.primary_image.original.url }}"
                                             class="attachment-lynessa_thumbnail size-lynessa_thumbnail" alt="img" width="600" height="778">
                                    </a>
                                </td>
                                <td class="product-name">
                                    <a href="{% url 'shop:view_product' product.product.slug %}">{{ product.product.name }}</a>
                                    <a href="#" class="button yith-wcqv-button" data-product_id="29">Quick View</a></td>
                                <td class="product-price">
                                    <span class="lynessa-Price-amount amount"><span class="lynessa-Price-currencySymbol">₹</span>{{ product.product.price }}</span></td>
                                <td class="product-stock-status">
                                    <span class="wishlist-in-stock">In Stock</span></td>
                                <td class="product-add-to-cart">
                                    <!-- Date added -->
                                    <!-- Add to cart button -->
                                    <a onclick="add_to_cart({{ product.product.id }})" data-quantity="1" class="button product_type_simple add_to_cart_button ajax_add_to_cart add_to_cart button alt"
                                       data-product_id="" data-product_sku="003D754"
                                       aria-label="Add “Abstract Sweatshirt” to your cart"
                                       rel="nofollow"> Add to Cart</a>
                                    <!-- Change wishlist -->
                                </td>
                                <td>
                                    <a href="{% url 'shop:wishlist-delete' product.product.id %}">
                                        <i class="fa fa-trash" style="font-size: 20px" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="6">
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
    {% include 'common/footer.html' %}
    <script>
        function add_to_cart(product_id) {
            var xhttp = new XMLHttpRequest();
            var params = 'product_id=' + product_id + ';is_ajax=1';

            xhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    console.log(this)
                    document.getElementById('header_count').innerHTML = this.response
                }
            };
            {#xhttp.open("POST", "add-to-cart", true);#}
            xhttp.open("POST", "{% url 'shop:add_to_cart' %}", true);
            xhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
            xhttp.send(params);
        }
    </script>
{#    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}
{#    <script src="{% static 'js/chosen.min.js' %}"></script>#}
{#    <script src="{% static 'js/countdown.min.js' %}"></script>#}
{#    <script src="{% static 'js/jquery.scrollbar.min.js' %}"></script>#}
{#    <script src="{% static 'js/lightbox.min.js' %}"></script>#}
{#    <script src="{% static 'js/magnific-popup.min.js' %}"></script>#}
{#    <script src="{% static 'js/slick.js' %}"></script>#}
{#    <script src="{% static 'js/jquery.zoom.min.js' %}"></script>#}
{#    <script src="{% static 'js/threesixty.min.js' %}"></script>#}
{#    <script src="{% static 'js/jquery-ui.min.js' %}"></script>#}
{#    <script src="{% static 'js/mobilemenu.js' %}"></script>#}
{#    <script src="{% static 'js/functions.js' %}"></script>#}
    </body>
{% endblock %}